name: Patch bundle updater

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  check_for_updates:
    name: Check for bundle updates
    runs-on: ubuntu-latest

    outputs:
      has_changes: ${{ steps.check_changes.outputs.has_changes }}
      changed_files: ${{ steps.find_commit.outputs.changed_files }}
      commit_link: ${{ steps.get_commit_link.outputs.commit_link }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests httpx
        working-directory: ${{ github.workspace }}

      - name: Run generate_bundles.py
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install requests httpx
          python generate_bundles.py
        working-directory: ${{ github.workspace }}

      - name: Set up Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote rm origin
          git remote add origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        shell: bash

      - name: Check for changes
        id: check_changes
        run: |
          source venv/bin/activate
          if git diff --quiet HEAD^ -- '*.json'; then
            echo "::set-output name=has_changes::false"
          else
            echo "::set-output name=has_changes::true"
          fi

      - name: Run find_commit.py and Get commit link
        id: get_commit_link
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          source venv/bin/activate
          python find_commit.py > commit_link.txt
          echo "::set-output name=commit_link::$(cat commit_link.txt)"

      - name: Find commit for changed files
        id: find_commit
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          source venv/bin/activate
          changed_files=$(git diff --name-only HEAD^ -- '*.json')
          if [ -z "$changed_files" ]; then
            echo "::set-output name=changed_files::"
          else
            echo "::set-output name=changed_files::$changed_files"
          fi

      - name: Finalize and commit changes
        if: success() && steps.check_changes.outputs.has_changes == 'true'
        run: |
          source venv/bin/activate
          git add *.json
          git diff --cached --quiet || (git commit -m "Update patch-bundle.json to latest" && git pull && git push origin HEAD:${{ github.ref }} --follow-tags)

      - name: Push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: bundles

      - name: Wait for 10 seconds
        if: steps.check_changes.outputs.has_changes == 'true'
        run: sleep 10s

      - name: Create artifact of changed files
        if: steps.check_changes.outputs.has_changes == 'true' && steps.find_commit.outputs.changed_files != ''
        run: |
          cat changed_files.txt > temp.txt
          echo "" >> temp.txt
          cat commit_link.txt >> temp.txt
          mv temp.txt changed_files.txt
          cat changed_files.txt
        working-directory: ${{ github.workspace }}
        uses: actions/upload-artifact@v2
        with:
          name: changed_files
          path: changed_files.txt
