name: Generate Commit Artifact

on:
  workflow_run:
    workflows: ["Patch bundle updater"]
    types:
      - completed

jobs:
  generate_commit_artifact:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Debug event payload
        run: echo "${{ toJson(github.event) }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install requests
        run: pip install requests

      - name: Download latest artifact from Patch bundle updater workflow
        id: download_artifact
        uses: actions/download-artifact@v2
        with:
          name: find_commit_output
          path: find_commit_output.txt

      - name: Check if artifact was downloaded
        run: |
          if [ ! -f "find_commit_output.txt" ]; then
            echo "Error: Artifact not found. Cancelling the workflow."
            exit 1
          fi
        if: ${{ steps.download_artifact.outputs.artifact_downloaded == 'true' }}

      - name: Run find_commit.py and create artifact
        run: |
          python find_commit.py > find_commit_output.txt
          echo "Commit link: $(cat find_commit_output.txt)"
        shell: bash

      - name: Upload find_commit output artifact
        uses: actions/upload-artifact@v2
        with:
          name: find_commit_output
          path: find_commit_output.txt
