name: Patch bundle updater

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  check_for_updates:
    name: Check for bundle updates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.x'

      - name: Set up virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install requests httpx
        working-directory: ${{ github.workspace }}

      - name: Run generate_bundles.py
        run: |
          source venv/bin/activate
          python generate_bundles.py
        working-directory: ${{ github.workspace }}

      - name: Check for changes
        id: check_changes
        run: |
          source venv/bin/activate
          git fetch
          if git diff --quiet HEAD^ -- '*.json'; then
            echo "has_changes=false" >> $GITHUB_ENV
          else
            echo "has_changes=true" >> $GITHUB_ENV
            echo "Changed files:" > changed_files.txt
            git diff --name-only HEAD^ -- '*.json' >> changed_files.txt
          fi
        working-directory: ${{ github.workspace }}
        env:
          has_changes: ${{ steps.check_changes.outputs.has_changes }}

  find_commit:
    name: Find commit for changed files
    runs-on: ubuntu-latest
    needs: check_for_updates
    
    if: ${{ needs.check_for_updates.outputs.has_changes == 'true' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up virtual environment
        run: python -m venv venv
        working-directory: ${{ github.workspace }}

      - name: Activate virtual environment and install dependencies
        run: |
          source venv/bin/activate
          python -m pip install requests httpx
        working-directory: ${{ github.workspace }}

      - name: Find commit for changed files
        run: |
          source venv/bin/activate
          python find_commit.py
        working-directory: ${{ github.workspace }}

      - name: Create artifact of changed files
        uses: actions/upload-artifact@v4.3.3
        with:
          name: changed_files
          path: changed_files.txt
        if: success()

      - name: Finalize and commit changes
        if: success() && needs.check_for_updates.outputs.has_changes == 'true'
        run: |
          source venv/bin/activate
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote set-url origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git add *.json
          git diff --cached --quiet || (git commit -m "Update patch-bundle.json to latest" && git push origin HEAD:${{ github.ref }} --follow-tags)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{ github.workspace }}

      - name: Push changes
        if: success() && needs.check_for_updates.outputs.has_changes == 'true'
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: bundles
