name: Bundle updater commit puller

on:
  push:
    branches:
      - main

jobs:
  find-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run find_commit.py
        run: python find_commit.py

      - name: Archive artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: commit-link
          path: changed_files.txt
