name: Bundle updater commit puller

on:
  workflow_run:
    workflows: ["Patch bundle updater"]
    types:
      - completed

jobs:
  get-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download Prior Artifact
        id: download_artifact
        uses: benday-inc/download-latest-artifact@main
        with:
          token: ${{ secrets.GIT_TOKEN }}
          repository_owner: 'Jman-Github'
          repository_name: 'ReVanced-Patch-Bundles'
          workflow_name: 'bundle-updater.yml'
          branch_name: 'bundles'
          artifact_name: 'changed_files'
          download_path: 'ReVanced-Patch-Bundles'

      - name: Check if artifact was downloaded
        run: |
          if [ ! -f "ReVanced-Patch-Bundles/changed_files" ]; then
            echo "No artifact found. Cancelling workflow."
            exit 0
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run find_commit.py script
        run: |
          python ReVanced-Patch-Bundles/find_commit.py

      - name: Create commit link artifact
        uses: actions/upload-artifact@v2
        with:
          name: commit-link
          path: commit-link.txt