name: Patch bundle updater

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
    
jobs:
  update_bundle:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        minutes: [1, 2, 3]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          persist-credentials: false
          fetch-depth: 0
    
    - name: Set up generate_bundles.py
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
      
    - name: Run generate_bundles.py
      run: |
        pip install httpx
        python generate_bundles.py
      
    - name: Check for changes
      id: check_changes
      run: |
        git diff --quiet && echo "::set-output name=changes::false" || echo "::set-output name=changes::true"
      continue-on-error: true
      
    - name: Finalize and commit changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add *.json
        git commit -m "updated patch-bundle.json to latest"
        git pull --rebase
        git push
        
    - name: Push changes
      if: matrix.minutes == 3
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
        branch: bundles

    # Pause the workflow for one minute before running again
    - name: Pause
      if: matrix.minutes != 3
      run: sleep 60

    # Trigger Discord notification if there are changes in .json files and this is the last repeat/pause
    - name: Discord notification
      if: matrix.minutes == 3 && steps.check_changes.outputs.changes == 'true'
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed. Some of patch-bundle.json files have been updated.'
