name: Patch bundle updater

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  check_for_updates:
    name: Check for bundle updates
    runs-on: ubuntu-latest

    outputs:
      has_changes: ${{ steps.check_changes.outputs.has_changes }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests httpx
        working-directory: ${{ github.workspace }}

      - name: Run generate_bundles.py
        id: run_generate_bundles
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install requests httpx
          output=$(python generate_bundles.py)
          echo "$output"
          if [[ $output == *"Your branch is up to date with 'origin/bundles'."* ]]; then
            echo "No changes found. Exiting..."
            exit
          fi
          git add '*.json'
          git diff --cached --quiet || (git commit -m "Update patch-bundle.json to latest" && git push origin HEAD:${{ github.ref }} --follow-tags)
        working-directory: ${{ github.workspace }}

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet HEAD^ -- '*.json'; then
            echo "::set-output name=has_changes::false"
          else
            echo "::set-output name=has_changes::true"
          fi

      - name: Push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: bundles

  find_commit_for_changed_files:
    name: Find commit for changed files
    runs-on: ubuntu-latest
    needs: check_for_updates
    if: needs.check_for_updates.outputs.has_changes == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
        working-directory: ${{ github.workspace }}

      - name: Find commit for changed files
        id: find_commit
        run: |
          changed_files=$(python find_commit.py)
          if [ -z "$changed_files" ]; then
            echo "::set-output name=changed_files::"
          else
            echo "$changed_files" > changed_files.txt
            echo "::set-output name=changed_files::changed_files.txt"
          fi

      - name: Create artifact of changed files
        if: steps.find_commit.outputs.changed_files != ''
        uses: actions/upload-artifact@v4.3.3
        with:
          name: changed_files
          path: changed_files.txt