name: Close labeled issues

on:
  issues:
    types: [labeled]

jobs:
  close-labeled-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Close labeled issues
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          LABELS="like unlike-mutable like-mutable"
          
          for label in $LABELS; do
            echo "Checking for issues with label $label"
            ISSUE_URLS=$(curl -sS -H "Authorization: token $TOKEN" "https://api.github.com/repos/${{ github.repository }}/issues?state=open&labels=$label" | jq -r '.[] | .url')
            
            for url in $ISSUE_URLS; do
              echo "Closing issue $url"
              curl -X PATCH -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" "$url" -d '{"state":"closed"}'
            done
          done
