name: Check and Update Patch-Bundle.json

on:
  workflow_run:
    workflows: ["Bundle updater commit puller", "Patch bundle updater"]
    types:
      - completed

jobs:
  check_and_update:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact from Bundle updater commit puller
        uses: benday-inc/download-latest-artifact@main
        if: ${{ github.event.workflow_run.name == 'Bundle updater commit puller' }}
        id: download_bundle_updater_artifact
        with:
          token: ${{ secrets.GIT_TOKEN }}
          repository_owner: 'Jman-Github'
          repository_name: 'ReVanced-Patch-Bundles'
          workflow_name: 'Bundle updater commit puller'
          download_path: 'commit-link'
          download_filename: 'commit-link.zip'

      - name: Unzip Bundle updater artifact
        if: steps.download_bundle_updater_artifact.outputs.download_success == 'true'
        run: unzip bundle_updater_artifact/changed_files.zip -d bundle_updater_artifact

      - name: Download Artifact from Patch bundle updater
        uses: benday-inc/download-latest-artifact@main
        if: github.event.workflow_run.name == 'Patch bundle updater'
        id: download_patch_updater_artifact
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository_owner: 'Jman-Github'
          repository_name: 'ReVanced-Patch-Bundles'
          workflow_name: 'Patch bundle updater'
          download_path: 'changed_files'
          download_filename: 'changed_files.zip'

      - name: Unzip Patch bundle updater artifact
        if: steps.download_patch_updater_artifact.outputs.download_success == 'true'
        run: unzip patch_updater_artifact/changed_files.zip -d patch_updater_artifact

      - name: Combine changes from both artifacts
        run: |
          cp -r bundle_updater_artifact/. patch_updater_artifact/.
          cd patch_updater_artifact
          zip -r combined_files.zip .

      - name: Send Discord Notification
        if: steps.download_bundle_updater_artifact.outputs.download_success == 'true' || steps.download_patch_updater_artifact.outputs.download_success == 'true'
        uses: tsickert/discord-webhook@v6.0.0
        with:
         webhook-url: ${{ secrets.WEBHOOK_URL }}
         embed-title: 'Patch-Bundle.json File(s) Updated'
         embed-description: |
          Patch-bundle.json file(s) have been successfully updated by the [Patch Bundle Updater Workflow](https://github.com/Jman-Github/ReVanced-Patch-Bundles/actions/workflows/bundle-updater.yml).
          
          **Changes:**
          ${{ steps.read_change_bundles.outputs.change_bundles }}
         embed-color: 65280
         embed-author-name: 'Patch Bundle Updater Workflow'
         embed-author-icon-url: 'https://github.gallerycdn.vsassets.io/extensions/github/vscode-github-actions/0.26.2/1694016984133/Microsoft.VisualStudio.Services.Icons.Default'
         embed-thumbnail-url: 'https://cdn-icons-png.flaticon.com/512/5278/5278658.png'
         username: 'ReVanced-Patch-Bundles'
         avatar-url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzUECg_ITr7YkE2pYiVdHqTxlg3wLwXKXIQrcxEBKd7Q&s'
