name: Discord Notification on JSON Change

on:
  workflow_dispatch:
  push:
    paths:
      - '**.json'

jobs:
  send_discord_notification:
    name: Send Discord Notification
    if: github.event_name == 'push' && steps.check_changes.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          pip install httpx
      
      - name: Send Discord Notification
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: 'A JSON file has been changed.'
          username: 'ReVanced-Patch-Bundles'
          avatar-url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzUECg_ITr7YkE2pYiVdHqTxlg3wLwXKXIQrcxEBKd7Q&s'
          raw-data: hi.json

  check_for_json_changes:
    name: Check for JSON changes
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet HEAD^ -- '*.json'; then
            echo "No changes"
            echo "::set-output name=has_changes::false"
          else
            echo "Changes found"
            echo "::set-output name=has_changes::true"
          fi
