name: Discord Notification on JSON Change

on:
  push:
    paths:
      - '**.json'
      - '.github/workflows/bundle-updater.yml'

jobs:
  send_discord_notification:
    name: Send Discord Notification
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, 'Update patch-bundle.json to latest') && contains(github.event.head_commit.message, '.json') }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: bundle-json
          path: artifacts
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Check for JSON modification
        id: check_json_modification
        run: |
          json_files=""
          commit_link=""
          for file in ${{ github.workspace }}/artifacts/*; do
            if [[ ${file} == *.json ]]; then
              json_files="${json_files}$(basename ${file}), "
            fi
          done
          if [ -n "$json_files" ]; then
            json_files="${json_files::-2}"
            commit_link="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
            echo "::set-output name=json_modified::true"
            echo "::set-output name=json_files::${json_files}"
            echo "::set-output name=commit_link::${commit_link}"
          else
            echo "::set-output name=json_modified::false"
          fi
        shell: bash
        
      - name: Send Discord Notification
        if: steps.check_json_modification.outputs.json_modified == 'true'
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          embed-title: 'Patch-Bundle.json File(s) Updated'
          embed-description: "Patch-bundle.json file(s) have been successfully updated by the [Patch Bundle Updater Workflow](${{ steps.check_json_modification.outputs.commit_link }})."
          embed-color: 65280
          embed-author-name: 'Patch Bundle Updater Workflow'
          embed-author-icon: 'https://github.gallerycdn.vsassets.io/extensions/github/vscode-github-actions/0.26.2/1694016984133/Microsoft.VisualStudio.Services.Icons.Default'
          embed-thumbnail-url: 'https://cdn-icons-png.flaticon.com/512/5278/5278658.png'
          username: 'ReVanced-Patch-Bundles'
          avatar-url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzUECg_ITr7YkE2pYiVdHqTxlg3wLwXKXIQrcxEBKd7Q&s'
