name: Discord Notification on JSON Change

on:
  push:
    paths:
      - '*.json'
    # Check if push is done by GitHub Actions
    branches:
      - bundles

  workflow_run:
    workflows: ["Patch bundle updater"]
    types:
      - completed

jobs:
  send_discord_notification:
    name: Send Discord Notification
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_run' && github.event.workflow_run.name == 'Patch bundle updater'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Check for JSON changes
        id: check_changes
        run: |
          if git diff --quiet HEAD^ -- '*.json'; then
            echo "No changes"
            echo "::set-output name=has_changes::false"
          else
            echo "Changes found"
            echo "::set-output name=has_changes::true"
          fi
          
      - name: Send Discord Notification
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "content": "A JSON file has been changed.",
            "username": "ReVanced-Patch-Bundles",
            "avatar_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzUECg_ITr7YkE2pYiVdHqTxlg3wLwXKXIQrcxEBKd7Q&s"
          }' ${{ secrets.WEBHOOK_URL }}
