name: Discord Notification on JSON Change

on:
  workflow_run:
    workflows: ["Patch bundle updater"]
    types:
      - completed

jobs:
  send_discord_notification:
    name: Send Discord Notification
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download changed files artifact
        uses: actions/download-artifact@v2
        with:
          name: changed_files
          path: ./artifacts

      - name: Check for JSON modification
        id: check_json_modification
        run: |
          if [ -f "./artifacts/changed_files.zip" ]; then
            echo "::set-output name=json_modified::true"
            echo "::set-output name=json_files::$(cat ./artifacts/changed_files.txt)"
          else
            echo "::set-output name=json_modified::false"
          fi
          
      - name: Send Discord Notification
        if: steps.check_json_modification.outputs.json_modified == 'true'
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          embed-title: 'Patch-Bundle.json File(s) Updated'
          embed-description: "Patch-bundle.json file(s) have been successfully updated by the [Patch Bundle Updater Workflow](https://github.com/Jman-Github/ReVanced-Patch-Bundles/actions/workflows/bundle-updater.yml). Files updated: ${{ steps.check_json_modification.outputs.json_files }}"
          embed-color: 65280
          embed-author-name: 'Patch Bundle Updater Workflow'
          embed-author-icon: 'https://github.gallerycdn.vsassets.io/extensions/github/vscode-github-actions/0.26.2/1694016984133/Microsoft.VisualStudio.Services.Icons.Default'
          embed-thumbnail-url: 'https://cdn-icons-png.flaticon.com/512/5278/5278658.png'
          username: 'ReVanced-Patch-Bundles'
          avatar-url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzUECg_ITr7YkE2pYiVdHqTxlg3wLwXKXIQrcxEBKd7Q&s'
