name: Discord webhook sender

on:
  workflow_run:
    workflows: ["Commit puller"]
    types:
      - completed

jobs:
  check_and_update:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact from Patch bundle updater
        id: download_patch_bundle_updater_artifact
        uses: benday-inc/download-latest-artifact@main
        with:
          token: ${{ secrets.GIT_TOKEN }}
          repository_owner: 'Jman-Github'
          repository_name: 'ReVanced-Patch-Bundles'
          branch_name: 'bundles'
          artifact_name: 'changed_files'
          workflow_name: 'Patch bundle updater'
          download_path: 'ReVanced-Patch-Bundles'
          download_filename: 'changed_files.zip'

      - name: Download Artifact from Commit puller
        id: download_commit_puller_artifact
        uses: benday-inc/download-latest-artifact@main
        with:
          token: ${{ secrets.GIT_TOKEN }}
          repository_owner: 'Jman-Github'
          repository_name: 'ReVanced-Patch-Bundles'
          branch_name: 'bundles'
          artifact_name: 'commit-link'
          workflow_name: 'Commit puller'
          download_path: 'ReVanced-Patch-Bundles'
          download_filename: 'commit-link.zip'

      - name: Create patch bundle updater artifact directory
        run: mkdir -p ReVanced-Patch-Bundles/patch_bundle_updater_artifact

      - name: Create commit puller artifact directory
        run: mkdir -p ReVanced-Patch-Bundles/commit_puller_artifact

      - name: Unzip Patch bundle updater artifact
        run: unzip ReVanced-Patch-Bundles/changed_files.zip -d ReVanced-Patch-Bundles/patch_bundle_updater_artifact

      - name: Unzip Commit puller artifact
        run: unzip ReVanced-Patch-Bundles/commit-link.zip -d ReVanced-Patch-Bundles/commit_puller_artifact

      - name: Set changes variable
        id: set_changes
        run: |
          changes=$(cat ReVanced-Patch-Bundles/patch_bundle_updater_artifact/changed_files.txt)
          
          if [ -z "$changes" ]; then
            changes="No changes"
          fi
          echo "::set-output name=changes::${changes}"
          
          # Send each line of changed_files.txt as a separate variable
          mapfile -t changes_array < ReVanced-Patch-Bundles/patch_bundle_updater_artifact/changed_files.txt
          changes_json="["
          for ((i=0; i<${#changes_array[@]}; i++)); do
            changes_json+="\"${changes_array[$i]}\\n\","
          done
          changes_json="${changes_json%,}"
          changes_json+="]"
          echo "::set-output name=changes_json::$changes_json"
          
      - name: Send Discord Notification
        uses: tsickert/discord-webhook@master
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: '||@everyone||'
          embed-title: 'Patch-Bundle.json File(s) Updated'
          embed-description: |
            Patch-bundle.json file(s) have been successfully updated by the [Patch Bundle Updater Workflow](https://github.com/Jman-Github/ReVanced-Patch-Bundles/actions/workflows/patch-bundle-updater.yml).
            
            **Changes:**
            ```
            ${{ steps.set_changes.outputs.changes }}
            ```
            **Changed:**
            ```
            ${{ join(fromJson(steps.set_changes.outputs.changes_json), '') }}
            ```
          embed-color: '65280'
          embed-author-name: 'Patch Bundle Updater Workflow'
          embed-author-icon-url: 'https://github.gallerycdn.vsassets.io/extensions/github/vscode-github-actions/0.26.2/1694016984133/Microsoft.VisualStudio.Services.Icons.Default'
          embed-thumbnail-url: 'https://cdn-icons-png.flaticon.com/512/5278/5278658.png'
          username: 'ReVanced-Patch-Bundles'
          avatar-url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzUECg_ITr7YkE2pYiVdHqTxlg3wLwXKXIQrcxEBKd7Q&s'