name: Discord Notification

on:
  workflow_run:
    workflows:
      - 'Patch bundle updater'
    types:
      - completed

jobs:
  send_discord_notification:
    if: ${{ github.event.workflow == 'Patch bundle updater' && github.event.workflow_run.conclusion == 'success' && env.has_json_changes == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send Discord notification
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          webhook-profile-url: 'https://cdn.pixabay.com/photo/2022/01/30/13/33/github-6980894_1280.png'
          webhook-profile-name: 'ReVanced-Patch-Bundle'
          content: 'Changes detected in a JSON file in ${{ github.repository }}.'
          embed-title: 'JSON File Updated'
          embed-description: 'Changes detected in a JSON file.'
