name: Add Like
on:
  issues:
    types:
      - labeled
jobs:
  add-like:
    env:
      author: ${{github.event.issue.user.login}}
    if: github.event.label.name == 'like'
    runs-on: ubuntu-latest
    name: commit and push like
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
        ref: bundles
    - name: Create local changes
      run: |
        if grep -Fxq "$author" likers.txt
        then
          echo "Try again!"
        else
          echo "$author" >> likers.txt
          #and update counter
          LIKES=$(wc -l < likers.txt)
          REPLACE=$(echo "<sub><b><i>Like counter: ${LIKES}</i></b></sub>")
          (head -9 README.md; echo "$REPLACE"; tail -n +11 README.md) > foobar && mv foobar README.md
        fi
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add like by $author"
    - name: Push changes
      run: |
        git push origin HEAD:bundles
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
