name: Check for compose manager updates

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  get-artifact-url-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: |
          sudo apt-get install jq -y
          python -m pip install requests

      - name: Get artifact URL and run Python script
        run: |
            ARTIFACT_ID=$(curl -sS "https://api.github.com/repos/ReVanced/revanced-manager/actions/workflows/pr-build.yml/runs?event=pull_request&status=success" | jq -r '.workflow_runs[0].artifacts_url' | cut -d"/" -f 10)
            if [ -z "$ARTIFACT_ID" ]; then
              echo "Failed to fetch artifact ID."
              exit 1
            fi
            ARTIFACT_DOWNLOAD_URL="https://github.com/ReVanced/revanced-manager/actions/artifacts/$ARTIFACT_ID/zip"
            echo "ARTIFACT_URL=$ARTIFACT_DOWNLOAD_URL" >> $GITHUB_ENV
            curl -sSL -o artifact.zip "$ARTIFACT_DOWNLOAD_URL"
            unzip -q artifact.zip -d artifact
            python get_compose_artifact.py
        
    
        
        
        