name: Check for compose manager updates

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  get-artifact-url:
    runs-on: ubuntu-latest
    outputs:
      artifact_url: ${{ steps.get_artifact_url.outputs.artifact_url }}
    steps:
      - name: Get artifact URL
        id: get_artifact_url
        run: |
          ARTIFACT_ID=$(curl -sS "https://api.github.com/repos/ReVanced/revanced-manager/actions/workflows/pr-build.yml/runs?event=pull_request&status=success" | jq -r '.workflow_runs[0].id')
          ARTIFACT_DOWNLOAD_URL=$(curl -sS "https://api.github.com/repos/ReVanced/revanced-manager/actions/runs/$ARTIFACT_ID/artifacts" | jq -r '.artifacts[0].archive_download_url')
          echo "::set-output name=artifact_url::$ARTIFACT_DOWNLOAD_URL"

  download-and-run:
    needs: get-artifact-url
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: |
          sudo apt-get install jq -y
          python -m pip install requests

      - name: Download and extract artifact
        run: |
          wget -O artifact.zip "${{ needs.get-artifact-url.outputs.artifact_url }}"
          unzip -q artifact.zip -d artifact

      - name: Run Python script
        run: |
          python get_compose_artifact.py
